- name: Firebase Deployment
  # You may pin to the exact commit or the version.
  # uses: sws2apps/firebase-deployment@31c47fb8bc4e424bba835c3f29a710d1f9607ad9
  uses: sws2apps/firebase-deployment@v3.2.0
  with:
    # The full identifier of the Workload Identity Provider, including the project number, pool name, and provider name. This must be the full identifier which includes all parts
    workloadIdentityProvider: 
    # Email address or unique identifier of the Google Cloud service account for which to generate credentials
    serviceAccount: 
    # Name of the firebase project you will deploy the site
    project: 
    # Path to the firebase.json config file
    config: # optional
    # Deploy only firebase functions
    function: # optional
    # Deploy only hosting site
    hosting: # optional
